### ISSUE TITLE
Explore how to get current time and how to write to file for error log capturing

### ISSUE THREAD

**Issue by wzul** [STIW3054/Repo2#25]
1. The time must be in readable format.
2. Create class to handle error log file writing

**Comment by AminAsyraf94** [comment]
owkeyy

**Comment by AminAsyraf94** [comment]
so let me get this straight..
i need to write the error log in text file,right? 
ke aku salah interpret question ni?

**Comment by AminAsyraf94** [comment]
https://examples.javacodegeeks.com/core-java/util/logging/write-log-entries-to-log-file/

nak buat log macam contoh ni kan? cuma nak kena letak dalam txt file kan?

**Comment by wzul** [comment]
100% betul
