### ISSUE TITLE
How to identify if the java belongs to specific java package?

### ISSUE THREAD

**Issue by wzul** [STIW3054/Repo2#41]
Situation: Compiling java file using **javac** will produce error if we call it directly (javac <filename>).

Real example:

```
javac ScanFile.java
ScanFile.java:3: error: package Folder does not exist
import Folder.Path;
             ^
ScanFile.java:28: error: cannot find symbol
        try (BufferedReader br = new BufferedReader(new FileReader(Path.getPath(pathFolder) + "\\" + file))) {
                                                                   ^
  symbol:   variable Path
  location: class ScanFile
Note: ScanFile.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

How to fix?

**Comment by AminAsyraf94** [comment]
It should be simple as we can identify if the java file belongs to specific package by looking at the package statement.

Based on the package statement, replace the dots "." with File.separator.

**Comment by wzul** [comment]
Check how deep the file reside in the folder directory and change to upper directory depending on package deep level.

**Comment by amsyarrazak** [comment]
Since compiling java source to bytecode doesn't require to calling full package name, this is not the case.

However, to run the compiled java source code requires to call with package name:

```
java <packageName>.<javaSourceCode>
```
